AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  EnforcedStyle: slashes

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30
  CountAsOne: ['array', 'hash', 'heredoc']

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120
